language: php
php:
  - '7.2'

services:
  - mysql

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

before_install:
  - composer self-update

install:
  - make install@test

script:
  - make test@test
